### PR TITLE
fix(sql): don't panic on missing migration when preload is enabled

### LINKED ISSUE #1930: SQL Plugin: The `preload` parameter has a potential `migration` requirement.
# Problem
When setting up the sql plugin, the ‘preload’ parameter is only used for migrations and assumes that the migration is given

https://github.com/tauri-apps/plugins-workspace/blob/7e1c17a635f10d69e10ea9f35081a68c71276203/plugins/sql/src/lib.rs#L145-L153

This does not seem to match its semantics.

If I use the SQL plugin and give a `preload` parameter but don't provide any migrations, the programme reports the following panic message
image

This is very unintuitive, and although `preload` is currently only used by `migration`, it would be better to report an error like `no migration providing`.

# Improvements

I have the following ideas to fix the current problem
1. rename `preload` to something else related to `migration`, such as `migration-preload`.
2. `preload` is not only used for migrations, but also for opening connections and managing them
3. provide a more user friendly panic message

### PR DESCRIPTION
**Pull request by Goodjooy**
this pr is the implement of #1930 .

# tasks
- [x] skip migration if no migration provided in preload

### CODE REVIEW

**Comment by FabianLars** [comment]
Thanks for the PR! I don't think we should panic here. I think i would have went with simply replacing the `unwrap()` that caused the panic with `unwrap_or_default()` so `preload` is basically ignored if no migrations were set.

**Comment by Goodjooy** [comment]
> Thanks for the PR! I don't think we should panic here. I think i would have went with simply replacing the `unwrap()` that caused the panic with `unwrap_or_default()` so `preload` is basically ignored if no migrations were set.

This solution is really simpler and fits the semantics of the `preload` itself, the code change is done

**Comment by Goodjooy** [comment]
Looks like CI is having trouble installing webkit2gtk. :(

**Comment by FabianLars** [comment]
oh, github changed the default runners

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
