### PR TITLE
Adding semver compatibility check for Windows and Linux

### PR DESCRIPTION
**Pull request by matthme**
Addressing #494 . This PR is assuming that this is desired default behavior. If it should rather be hidden behind a feature flag, I can try to add that.

### CODE REVIEW

**Review by amrbashir — DISMISSED** [review]
The implementation looks alright, but I am not sure I like the compatibility thing though, I think mismatched versions, even if its a patch version shouldn't launch a different version.

However, I think this maybe a desired behavior for some people so I'd suggest:
1. Add a behavior enum
	```rs
	enum LaunchBehavior {
		Same,
		#[cfg(feature = "compatible")]
		Compatible
	}
	```
2. Add a builder for the plugin that will have a method to specify which behavior they need
3. make the behavior that requires `semver` behind a feature flag just to not add unnecessary dependencies for default behavior.

does that sound alright?

**Comment by matthme** [comment]
Okay, I will try to add that when I have some time.

**Comment by qlaffont** [comment]
Any update on this one ?

**Comment by matthme** [comment]
I did not have time to implement the feature flag as it will probably take quite some time and I had lots of other things on my plate so far. For now I'm using my fork instead for my projects: https://github.com/matthme/plugins-workspace/tree/single-instance-semver maybe that's useful for you as well.

**Comment by FabianLars** [comment]
@amrbashir would it be alright to have the feature flag itself change the behavior?

**Comment by amrbashir** [comment]
I guess so yeah

**Comment by FabianLars** [comment]
coolio. mainly asking cause i'm lazy 🙃

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
