### PR TITLE
add support for absolute sqlite db path in case of using tauri dialog…

### PR DESCRIPTION
**Pull request by syokensyo**
Since tauri provide dialog api, we can use it to browse files on the computer and get the file's absolute path, it is more flexible to make the sqlite plugin adapt to that, so user can operate on any sqlite db file in their computer, no need to put db file to the app's path anymore.

### CODE REVIEW

**Comment by FabianLars** [comment]
Thanks for contributing! Before anything else, to be able to merge this PR your commit must be [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) :)

Now about the change itself: i also worked on this half a year ago here: https://github.com/tauri-apps/plugins-workspace/pull/279.
I'm afraid that the implementation can't be as simple as in your PR since we have to support both `/` and `\` on all OSes, have to handle the stupid UAC path on Windows (the `\\?\` path prefix) and may or may not have to handle `sqlite:` and `sqlite://` at the same time since both are valid - in my PR i just added comments that only `sqlite://` is supported but not sure if i'm 100% happy with this decision.

**Comment by syokensyo** [comment]
Oh, sorry, didn't notice your PR, and yes you are right, I didn't cover enough scenarios, will look into your pr, and I think absolute path support is a frequency requirement for sqlite user, it's better to support limited scenarios than no scenario.

**Comment by amrbashir** [comment]
you could use `dunce` crate which will remove the UNC on Windows and keep the path as is on other platforms.

**Comment by syokensyo** [comment]
Will try it, thanks.

**Pull request closed without merging**
