### PR TITLE
feat: update to tauri v2 stable, promote all packages to 2.0.0

### PR DESCRIPTION
**Pull request by lucasfernog**

### CODE REVIEW

**Comment by FabianLars** [comment]
wasn't the idea to _not_ do this? don't care too much, i can introduce breaking changes in a non breaking way if needed, just surprised. I guess this is easier for consumers 🤷

**Comment by lucasfernog** [comment]
we agreed on possibly doing some breaking changes on minor releases - though we won't need that for the most used plugins out of the gate (but store, NFC rust api still needs some work)

**Comment by FabianLars** [comment]
ok

**Review by tweidinger — DISMISSED** [review]
🤞

**Pull request merged**
