### PR TITLE
[positioner] handleIconState in JS

### PR DESCRIPTION
**Pull request by jbolda**
## Motivation

We need to handle events to update the icon state in this plugin. Previously, we could only do this in Rust, which meant it was not possible create the TrayIcon in JS with an `action`. This adds a function to handle the same.

### CODE REVIEW

**Comment by jbolda** [comment]
I think our types might be wrong here.
image

**Comment by amrbashir** [comment]
@jbolda that is indeed the case, the Rust type is actually an enum:
```rs
enum Position {
  Physical { .. },
  Logical { .. },
}
```
and it will be serialized into 
```json
{
  "Physical or Logical": { .. }
}
```

So we need to at runtime, convert these values into the JS `PhysicalPosition` class

**Review by lucasfernog — APPROVED** [review]

**Comment by jbolda** [comment]
Looks like the JS vs Rust have a mismatch last commit. /cc @lucasfernog 
https://github.com/jbolda/stream-todo/pull/1/files#diff-28a82398545129d0c8905ddb24bf85b6d28af04026fb6d45394899bd1ad777ac

**Comment by amrbashir** [comment]
@jbolda  fixed in https://github.com/tauri-apps/plugins-workspace/pull/1858

**Pull request merged**
