### PR TITLE
feat(window-state): add flags to control what is saved/restored

### LINKED ISSUE #101: [window-state] persist to much information (decoration: true/false is persisted)
Only tested on Linux! Gnome 43

We have an app with `decorations: false` and used the window-state plugin.

We then changed our mind about the decorations and flipped the flag `decorations: true`

But if the window-state plugin has been started with decorations: false that state is restored, so our window doesn't get the decorations :)

### PR DESCRIPTION
**Pull request by amrbashir**
closes #101

### CODE REVIEW

**Comment by JonasKruckenberg** [comment]
I like this because our saving/restoring of the fullscreen property isn't handled correctly

**Comment by amrbashir** [comment]
> I like this because our saving/restoring of the fullscreen property isn't handled correctly

How so? as far as my testing goes, it saves/restores correctly

**Review by JonasKruckenberg — APPROVED** [review]
Works great in elk and with your PR that fullscreen restoring bug seems to be gone too 👍🏻

**Comment by FabianLars** [comment]
Before merging it we need to update the plugin's readme as it still shows the old ShowMode

**Comment by FabianLars** [comment]
2 seconds too slow lol

**Pull request merged**
