### PR TITLE
fix(notification): Add permission commands for Actions

### PR DESCRIPTION
**Pull request by naman-crabnebula**
- Added `register_action_types` and `register_listener` to Permission Commands
- Now, new Action types can be registered on Android and also used
- This is necessary path for working of notification actions on Android

### CODE REVIEW

**Comment by tillmann-crabnebula** [comment]
Could you please remove the `.js` file changes from the other plugins from this PR?
Found these to be unrelated but maybe I missed something.

Otherwise looks good to me and I already integrated the permissions mentioned here in #1460 👍

**Comment by FabianLars** [comment]
Also, since we were talking about permissions for mobile-only commands last week, do you still have an error message around? Or whatever made you look into this?

We have multiple mobile-only commands across a few plugins so it'd be good to know what to look out for.

**Comment by naman-crabnebula** [comment]
> Could you please remove the .js file changes from the other plugins from this PR? 

No, these are necessary. Also, most of the changes are auto-generated, only the `build.rs` file has been manually edited

> Also, since we were talking about permissions for mobile-only commands last week, do you still have an error message around? Or whatever made you look into this?

Yes, here is the error message

```
06-06 03:47:22.061 6918 6918 E Tauri/Console: File: http://tauri.localhost/main.js - Line 36 - Msg: Uncaught (in promise) notification.register_action_types not allowed. Permissions associated with this command:
```

I asked @lucasfernog about this error, and he suggested these changes.

**Comment by FabianLars** [comment]
> Yes, here is the error message

Okay cool, thanks! So i guess we @tillmann-crabnebula have to go over the mobile plugins tomorrow too 😂 (Edit: for https://github.com/tauri-apps/plugins-workspace/pull/1460)

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
