### PR TITLE
Fix/readme banners

### PR DESCRIPTION
**Pull request by lorenzolewis**
Updates the banners on the readme's to absolute paths so that downstream docs CI has nice banners

### CODE REVIEW

**Review by FabianLars — APPROVED** [review]

**Comment by amrbashir** [comment]
I feel like I prefer the relative path, which makes it resilient against branch name changing, merge conflicts, parent directory renaming ...etc. I feel like this is a problem that should be addressed downstream where the script that generates the docs for the README, should rewrite the relative URL to a permanent URL that reference the commit it was generated from.

**Comment by lorenzolewis** [comment]
How do other downstreams like docs.rs and npm handle this? I can look into what it would take to match whatever they're doing. I'd just copied what's done here: https://github.com/tauri-apps/tauri/blob/4db363a03c182349f8491f46ced258d84723b11f/core/tauri/README.md?plain=1#L3 (and in other packages there)

**Comment by FabianLars** [comment]
tbh I don't think any of the reasons listed really matter, at least in the short term, so imo we should focus on getting the docs running first and add this improvement to the Todo list for later :)

**Comment by amrbashir** [comment]
> How do other downstreams like docs.rs and npm handle this? I can look into what it would take to match whatever they're doing.

`Crates.io` seem to transform the relative link into an absolute URL, so `./splash.png` will become `https://raw.githubusercontent.com/tauri-apps/plugins-workspace/e47562f71284457ff77e4c8b6bf02fdbe19ab880/plugins/window-state/splash.png`

>  I'd just copied what's done here: [tauri-apps/tauri@`4db363a`/core/tauri/README.md?plain=1#L3](https://github.com/tauri-apps/tauri/blob/4db363a03c182349f8491f46ced258d84723b11f/core/tauri/README.md?plain=1#L3) (and in other packages there)

Yeah, we probably gonna need to fix those as well.

> tbh I don't think any of the reasons listed really matter, at least in the short term, so imo we should focus on getting the docs running first and add this improvement to the Todo list for later :)

I agree, I am not saying it is a blocker, just something to think about for the future.

**Pull request merged**
