### PR TITLE
Added quotes for cmd

### PR DESCRIPTION
**Pull request by TheRobustRoast**
fix for https://github.com/tauri-apps/plugins-workspace/issues/1804

### CODE REVIEW

**Review by Legend-Master — DISMISSED** [review]

**Review by Legend-Master — APPROVED** [review]

**Comment by Legend-Master** [comment]
Thanks

**Comment by FabianLars** [comment]
@Legend-Master did you check whether is_registered still works?

**Comment by Legend-Master** [comment]
Oops, didn't know we actually check the registry value instead of checking if it exists, I'll make PR to fix that

**Comment by FabianLars** [comment]
yeah that's to try to not return true when another app handles that same scheme (though that may need an explicit return type as simply overwriting would be a bit messed up)

**Pull request merged**
