### PR TITLE
add Position::TrayFixedLeft,TrayFixedRight,TrayFixedCenter

### PR DESCRIPTION
**Pull request by cauyxy**
In the updated code, three new window positions have been added to the Position enum: TrayFixedLeft, TrayFixedRight, and TrayFixedCenter. These new positions are similar to their respective counterparts TrayLeft, TrayRight, and TrayCenter. However, they take the target operating system into consideration when calculating the y-coordinate of the window position.

For the TrayFixedLeft, TrayFixedRight, and TrayFixedCenter positions, the code checks if the y-coordinate is less than 0. If it is, the y value is set differently based on the target OS:

On Windows: y is set to tray_y + tray_height
On macOS: y is set to tray_y
This ensures that the window is properly positioned relative to the system tray based on the specific behavior of the target operating system.

### CODE REVIEW

**Comment by cauyxy** [comment]
fix issue like [System Tray Overflow](https://github.com/lencx/ChatGPT/issues/725)

**Comment by FabianLars** [comment]
Hmm, i almost feel like this should be the default behavior 🤔 

I'll let Jonas review this since he wrote this Plugin (and i don't have access to macOS). He's on vacation rn so it may take a while :)

P.S. Thanks for contributing!

**Comment by lucasfernog** [comment]
I think this should be the default behavior too. Anything against this @JonasKruckenberg ?

**Comment by lucasfernog** [comment]
@cauyxy can you make this the default implementation so we can merge it?

```diff
diff --git a/plugins/positioner/src/ext.rs b/plugins/positioner/src/ext.rs
index 4160728..73520bf 100644
--- a/plugins/positioner/src/ext.rs
+++ b/plugins/positioner/src/ext.rs
@@ -113,18 +113,8 @@ impl<R: Runtime> WindowExt for Window<R> {
             },
             #[cfg(feature = "system-tray")]
             TrayLeft => {
-                if let Some((tray_x, tray_y)) = tray_position {
-                    PhysicalPosition {
-                        x: tray_x,
-                        y: tray_y - window_size.height,
-                    }
-                } else {
-                    panic!("Tray position not set");
-                }
-            }
-            #[cfg(feature = "system-tray")]
-            TrayFixedLeft => {
-                if let(Some((tray_x, tray_y)), Some((_, tray_height))) = (tray_position, tray_size) {
+                if let (Some((tray_x, tray_y)), Some((_, tray_height))) = (tray_position, tray_size)
+                {
                     let y = tray_y - window_size.height;
                     // Choose y value based on the target OS
                     #[cfg(target_os = "windows")]
@@ -151,19 +141,9 @@ impl<R: Runtime> WindowExt for Window<R> {
             }
             #[cfg(feature = "system-tray")]
             TrayRight => {
-                if let (Some((tray_x, tray_y)), Some((tray_width, _))) = (tray_position, tray_size)
+                if let (Some((tray_x, tray_y)), Some((tray_width, tray_height))) =
+                    (tray_position, tray_size)
                 {
-                    PhysicalPosition {
-                        x: tray_x + tray_width,
-                        y: tray_y - window_size.height,
-                    }
-                } else {
-                    panic!("Tray position not set");
-                }
-            }
-            #[cfg(feature = "system-tray")]
-            TrayFixedRight => {
-                if let(Some((tray_x, tray_y)), Some((tray_width, tray_height))) = (tray_position, tray_size) {
                     let y = tray_y - window_size.height;
                     // Choose y value based on the target OS
                     #[cfg(target_os = "windows")]
@@ -172,7 +152,10 @@ impl<R: Runtime> WindowExt for Window<R> {
                     #[cfg(target_os = "macos")]
                     let y = if y < 0 { tray_y } else { y };
 
-                    PhysicalPosition { x: tray_x + tray_width, y }
+                    PhysicalPosition {
+                        x: tray_x + tray_width,
+                        y,
+                    }
                 } else {
                     panic!("Tray position not set");
                 }
@@ -191,19 +174,8 @@ impl<R: Runtime> WindowExt for Window<R> {
             }
             #[cfg(feature = "system-tray")]
             TrayCenter => {
-                if let (Some((tray_x, tray_y)), Some((tray_width, _))) = (tray_position, tray_size)
-                {
-                    PhysicalPosition {
-                        x: tray_x + (tray_width / 2) - (window_size.width / 2),
-                        y: tray_y - window_size.height,
-                    }
-                } else {
-                    panic!("Tray position not set");
-                }
-            }
-            #[cfg(feature = "system-tray")]
-            TrayFixedCenter => {
-                if let (Some((tray_x, tray_y)), Some((tray_width, tray_height))) = (tray_position, tray_size)
+                if let (Some((tray_x, tray_y)), Some((tray_width, tray_height))) =
+                    (tray_position, tray_size)
                 {
                     let x = tray_x + tray_width / 2 - window_size.width / 2;
                     let y = tray_y - window_size.height;
```

**Comment by cauyxy** [comment]
> @cauyxy can you make this the default implementation so we can merge it?
> 
> ```diff
> diff --git a/plugins/positioner/src/ext.rs b/plugins/positioner/src/ext.rs
> index 4160728..73520bf 100644
> --- a/plugins/positioner/src/ext.rs
> +++ b/plugins/positioner/src/ext.rs
> @@ -113,18 +113,8 @@ impl<R: Runtime> WindowExt for Window<R> {
>              },
>              #[cfg(feature = "system-tray")]
>              TrayLeft => {
> -                if let Some((tray_x, tray_y)) = tray_position {
> -                    PhysicalPosition {
> -                        x: tray_x,
> -                        y: tray_y - window_size.height,
> -                    }
> -                } else {
> -                    panic!("Tray position not set");
> -                }
> -            }
> -            #[cfg(feature = "system-tray")]
> -            TrayFixedLeft => {
> -                if let(Some((tray_x, tray_y)), Some((_, tray_height))) = (tray_position, tray_size) {
> +                if let (Some((tray_x, tray_y)), Some((_, tray_height))) = (tray_position, tray_size)
> +                {
>                      let y = tray_y - window_size.height;
>                      // Choose y value based on the target OS
>                      #[cfg(target_os = "windows")]
> @@ -151,19 +141,9 @@ impl<R: Runtime> WindowExt for Window<R> {
>              }
>              #[cfg(feature = "system-tray")]
>              TrayRight => {
> -                if let (Some((tray_x, tray_y)), Some((tray_width, _))) = (tray_position, tray_size)
> +                if let (Some((tray_x, tray_y)), Some((tray_width, tray_height))) =
> +                    (tray_position, tray_size)
>                  {
> -                    PhysicalPosition {
> -                        x: tray_x + tray_width,
> -                        y: tray_y - window_size.height,
> -                    }
> -                } else {
> -                    panic!("Tray position not set");
> -                }
> -            }
> -            #[cfg(feature = "system-tray")]
> -            TrayFixedRight => {
> -                if let(Some((tray_x, tray_y)), Some((tray_width, tray_height))) = (tray_position, tray_size) {
>                      let y = tray_y - window_size.height;
>                      // Choose y value based on the target OS
>                      #[cfg(target_os = "windows")]
> @@ -172,7 +152,10 @@ impl<R: Runtime> WindowExt for Window<R> {
>                      #[cfg(target_os = "macos")]
>                      let y = if y < 0 { tray_y } else { y };
>  
> -                    PhysicalPosition { x: tray_x + tray_width, y }
> +                    PhysicalPosition {
> +                        x: tray_x + tray_width,
> +                        y,
> +                    }
>                  } else {
>                      panic!("Tray position not set");
>                  }
> @@ -191,19 +174,8 @@ impl<R: Runtime> WindowExt for Window<R> {
>              }
>              #[cfg(feature = "system-tray")]
>              TrayCenter => {
> -                if let (Some((tray_x, tray_y)), Some((tray_width, _))) = (tray_position, tray_size)
> -                {
> -                    PhysicalPosition {
> -                        x: tray_x + (tray_width / 2) - (window_size.width / 2),
> -                        y: tray_y - window_size.height,
> -                    }
> -                } else {
> -                    panic!("Tray position not set");
> -                }
> -            }
> -            #[cfg(feature = "system-tray")]
> -            TrayFixedCenter => {
> -                if let (Some((tray_x, tray_y)), Some((tray_width, tray_height))) = (tray_position, tray_size)
> +                if let (Some((tray_x, tray_y)), Some((tray_width, tray_height))) =
> +                    (tray_position, tray_size)
>                  {
>                      let x = tray_x + tray_width / 2 - window_size.width / 2;
>                      let y = tray_y - window_size.height;
> ```

Done

**Comment by JonasKruckenberg** [comment]
Also +1 on making this default behaviour, just make CI pass and we can merge this awesome fix! Thanks 👍🏻

**Review by JonasKruckenberg — DISMISSED** [review]

**Comment by FabianLars** [comment]
Since this was approved previously: We'll also need a changefile similar to https://github.com/tauri-apps/plugins-workspace/blob/v1/.changes/stronghold-argon2.md before we can merge it, thank you!

**Review by FabianLars — APPROVED** [review]
Thank you! Awesome work :)

**Pull request merged**
