### PR TITLE
set connectTimeout from Init

### PR DESCRIPTION
**Pull request by hygkui**

### CODE REVIEW

**Comment by amrbashir** [comment]
Could you add a change file in `.changes` directory?

**Comment by hygkui** [comment]
> Could you add a change file in `.changes` directory?

Yes, it's done.

**Review by amrbashir — DISMISSED** [review]

**Comment by amrbashir** [comment]
Thanks

**Comment by amrbashir** [comment]
looks like you need to run `pnpm build`

**Comment by hygkui** [comment]
> looks like you need to run `pnpm build`

Got it!

**Review by amrbashir — DISMISSED** [review]

**Comment by amrbashir** [comment]
@hygkui your last commit [`486cfe1` (#851)](https://github.com/tauri-apps/plugins-workspace/pull/851/commits/486cfe14a5bd51496febb46c14c0346b00369895) is not signed and I won't be able to merge now

**Comment by hygkui** [comment]
Ok, I will fix it.

**Comment by hygkui** [comment]
@amrbashir Thanks for your help, I think all is good this time :)

**Comment by amrbashir** [comment]
@hygkui unfortunately the commit still exists, you need to rebase and squash that commit or sign it.

**Comment by hygkui** [comment]
> @hygkui unfortunately the commit still exists, you need to rebase and squash that commit or sign it.

OK

**Pull request closed without merging**
