### PR TITLE
fix(deps): use no default features on tauri

### PR DESCRIPTION
**Pull request by Legend-Master**
Use no default features on tauri for all plugins so that consumers can use `default-features = false` on tauri

### CODE REVIEW

**Comment by Legend-Master** [comment]
Needs https://github.com/tauri-apps/tauri/pull/9954

**Comment by Legend-Master** [comment]
Hmm, all the iOS tests are failing but they did fine in the tauri repo https://github.com/tauri-apps/tauri/actions/runs/9754721776/job/26922051410

**Comment by lucasfernog** [comment]
Needs a Tauri patch unfortunately.

**Comment by FabianLars** [comment]
Is the iOS wry feature still required with Lucas's PR merged and released?

**Comment by Legend-Master** [comment]
I think so, Lucas's change file said

> Move `PluginApi::register_ios_plugin` behind the `wry` Cargo feature as `Webview::with_webview` is only available when that feature is enabled.

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
