### PR TITLE
refactor!(dialog): change `type` field in JS to `kind`

### LINKED ISSUE #944: Dialog type doesn't work when calling v2 dialog from js side
```js
message('1', { type: 'warning' })
```

image

### PR DESCRIPTION
**Pull request by Legend-Master**
Fix #944 

Before
```js
await invoke("plugin:dialog|confirm", {
	message: "1",
	type_: 'error',
});
```
image

After
```js
await invoke("plugin:dialog|confirm", {
	message: "1",
	type: 'error',
});
```
image

### CODE REVIEW

**Review by amrbashir — DISMISSED** [review]

**Comment by amrbashir** [comment]
I think the better choice here is to rename the `type` field to `kind` to match the Rust API.

**Review by amrbashir — APPROVED** [review]

**Comment by Legend-Master** [comment]
Yes, if we don't mind breaking the old API, I'm fine with both ways 😀

**Comment by amrbashir** [comment]
Yeah it is better to change now in beta than when stable.

**Comment by amrbashir** [comment]
Thanks for your contribution btw.

**Pull request merged**
